title: GUNDAM User Guide Explanatory Draft
description: Draft explanatory documentation for the GUNDAM User Guide, written by Xubowen Tao, an undergraduate student at Stony Brook University, as part of the 2026 NN Group Summer GUNDAM project.

theme: jekyll-theme-cayman
markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
